# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "waux"
description:        "a clean, lightweight and minimalistic blog theme for jekyll"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//kiko.gfjaru.com"
author:             "gfjaru"
twitter:
  username:         "gfjaru"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "/waux"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Home"
    href:           "/"
  - name:           "Cognitive"
    href:           "/cognitive"
  - name:           "Intellectual"
    href:           "/intellectual"
  - name:           "Collective"
    href:           "/collective"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
