# Basic
name:               "waux"
description:        "waux site"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "http//www.waux.com"
author:             "waux"
twitter:
  username:         "waux"
#facebook:
#  app_id:           1234
#    publisher:      1234
disqus:
  username: waux

# URL
baseurl:            "/waux"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Home"
    href:           "/"
  - name:           "Cognitive"
    href:           "/cognitive"
  - name:           "Intellectual"
    href:           "/intellectual"
  - name:           "Collective"
    href:           "/collective"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
